version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  versioning-strategy: increase-if-necessary
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - core23
  assignees:
  - core23
  labels:
  - dependency
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '03:00'
  open-pull-requests-limit: 10
  labels:
  - pedantic
  - automerge
